# Generated by Django 5.1.4 on 2025-04-07 11:40

from django.db import migrations

def copy_cpf_from_resume_to_user(apps, schema_editor):
    Resume = apps.get_model('hr', 'Resume')

    for resume in Resume.objects.all():
        if resume.cpf:
            user = resume.user
            user.cpf = resume.cpf
            user.save(update_fields=['cpf'])

def reverse_copy_cpf_from_user_to_resume(apps, schema_editor):
    Resume = apps.get_model('hr', 'Resume')

    for resume in Resume.objects.all():
        user = resume.user
        if user.cpf:
            resume.cpf = user.cpf
            resume.save(update_fields=['cpf'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_cpf'),
    ]

    operations = [
        migrations.RunPython(copy_cpf_from_resume_to_user, reverse_copy_cpf_from_user_to_resume),
    ]
