# Generated by Django 5.1.4 on 2025-02-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0013_client_benefits_alter_benefit_benefit'),
        ('hr', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayableTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, help_text='Data de emissão do título.', null=True)),
                ('supplier', models.CharField(blank=True, help_text='Nome do fornecedor.', max_length=100, null=True)),
                ('document_number', models.CharField(help_text='Número do documento referente ao título.', max_length=20, unique=True)),
                ('invoice_number', models.CharField(help_text='Número do boleto ou fatura.', max_length=60, unique=True)),
                ('due_date', models.DateField(blank=True, help_text='Data de vencimento do título.', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do título.', max_digits=12, null=True)),
                ('description', models.CharField(blank=True, help_text='Descrição breve do título.', max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Data em que o pagamento foi realizado.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro.')),
            ],
            options={
                'verbose_name': 'Título a pagar',
                'verbose_name_plural': 'Títulos a pagar',
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivableTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, help_text='Número do documento associado ao título.', max_length=15, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Data de vencimento do título.', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do título.', max_digits=12, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Data em que o pagamento foi realizado.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registro.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro.')),
                ('client', models.ForeignKey(default=1, help_text='Cliente associado ao título.', on_delete=django.db.models.deletion.PROTECT, related_name='receivable_titles', to='clients.client')),
                ('profile', models.ForeignKey(blank=True, help_text='Perfil associado ao título, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_titles', to='hr.profile')),
            ],
            options={
                'verbose_name': 'Título a receber',
                'verbose_name_plural': 'Títulos a receber',
            },
        ),
    ]
