# Generated by Django 5.1.4 on 2025-05-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_description'),
        ('finance', '0001_initial'),
        ('hr', '0028_alter_resume_linkedin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountsPayableTitle',
            new_name='PayableTitle',
        ),
        migrations.RenameModel(
            old_name='AccountsReceivableTitle',
            new_name='ReceivableTitle',
        ),
    ]
