# Generated by Django 5.1.4 on 2025-05-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_description'),
        ('finance', '0002_rename_accountspayabletitle_payabletitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivabletitle',
            name='client_contact',
            field=models.ForeignKey(default=1, help_text='Contato do cliente', on_delete=django.db.models.deletion.PROTECT, related_name='receivable_titles', to='clients.clientcontact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivabletitle',
            name='client',
            field=models.ForeignKey(help_text='Cliente associado ao título.', on_delete=django.db.models.deletion.PROTECT, related_name='receivable_titles', to='clients.client'),
        ),
    ]
