# Generated by Django 5.1.4 on 2025-05-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_receivabletitle_client_contact_and_more'),
        ('hr', '0029_alter_report_profile_alter_report_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivabletitle',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Parecer associado ao título', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_titles', to='hr.report'),
        ),
    ]
