# Generated by Django 5.1.4 on 2025-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_receivabletitle_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivabletitle',
            name='profile',
        ),
    ]
