# Generated by Django 5.1.4 on 2025-05-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_receivabletitle_profile'),
        ('hr', '0029_alter_report_profile_alter_report_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivabletitle',
            name='report',
        ),
        migrations.AddField(
            model_name='receivabletitle',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Perfil associado ao título, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_titles', to='hr.profile'),
        ),
        migrations.AddField(
            model_name='receivabletitle',
            name='reports',
            field=models.ManyToManyField(help_text='Parecer associado ao título', related_name='receivable_titles', to='hr.report'),
        ),
    ]
