# Generated by Django 5.1.4 on 2025-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_receivabletitle_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivabletitle',
            name='profile',
        ),
    ]
