# Generated by Django 5.1.4 on 2025-02-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=45)),
                ('marital_status', models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (4, 'Viúvo(a)')])),
                ('spouse_name', models.CharField(blank=True, help_text='Nome cônjuge', max_length=45, null=True)),
                ('spouse_profession', models.CharField(blank=True, max_length=45, null=True)),
                ('has_children', models.BooleanField(blank=True, null=True)),
                ('children_ages', models.CharField(blank=True, max_length=20, null=True)),
                ('is_smoker', models.BooleanField(default=False)),
                ('has_car', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('disability_cid', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=6)),
                ('complement', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=15)),
                ('contact_phone', models.CharField(blank=True, help_text='Telefone para contato', max_length=15, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('education_level', models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Ensino Médio Técnico'), (4, 'Tecnólogo'), (5, 'Graduação'), (6, 'Pós-graduação'), (7, 'Mestrado'), (8, 'Doutorado')])),
                ('education_details', models.TextField()),
                ('english_level', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Fluente')])),
                ('spanish_level', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Fluente')])),
                ('other_languages', models.CharField(blank=True, max_length=45, null=True)),
                ('computer_skills', models.TextField(blank=True, null=True)),
                ('additional_courses', models.TextField(blank=True, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('available_full_time', models.BooleanField(default=False, help_text='Horário comercial')),
                ('available_morning_afternoon', models.BooleanField(default=False, help_text='Manhã - Tarde')),
                ('available_afternoon_night', models.BooleanField(default=False, help_text='Tarde - Noite')),
                ('available_night_shift', models.BooleanField(default=False, help_text='Madrugada')),
                ('available_1236', models.BooleanField(default=False, help_text='Escala 12x36')),
                ('available_as_substitute', models.BooleanField(default=False, help_text='Folguista')),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('C', 'Cancelada'), ('S', 'Suspensa')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_positions', models.ManyToManyField(blank=True, related_name='resumes', to='hr.position')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('responsibilities', models.TextField()),
                ('reason_for_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='hr.resume')),
            ],
        ),
    ]
