# Generated by Django 5.1.4 on 2025-02-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Currículo', 'verbose_name_plural': 'Currículos'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
