# Generated by Django 5.1.4 on 2025-02-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_benefits_alter_benefit_benefit'),
        ('hr', '0004_alter_position_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_level',
            field=models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ET', 'Ensino Médio Técnico'), ('TE', 'Tecnólogo'), ('GR', 'Graduação'), ('PG', 'Pós-graduação'), ('ME', 'Mestrado'), ('DR', 'Doutorado')], help_text='Nível de escolaridade', max_length=2),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('M', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], help_text='Estado civil', max_length=1),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Data de criação do perfil.', null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('C', 'Cancelado'), ('S', 'Suspenso')], default='A', help_text='Status do perfil: Ativo (A), Inativo (I), Cancelado (C) ou Suspenso (S).', max_length=1)),
                ('deadline', models.IntegerField(blank=True, help_text='Prazo para preenchimento da vaga (em dias).', null=True)),
                ('estimated_delivery', models.DateField(blank=True, help_text='Previsão de entrega do perfil ao cliente.', null=True)),
                ('confidential', models.BooleanField(blank=True, help_text='Se marcado, indica que a vaga é sigilosa.', null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Quantidade de posições disponíveis para este perfil.', null=True)),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, help_text='Remuneração oferecida para a vaga.', max_digits=12, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do serviço de recrutamento.', max_digits=12, null=True)),
                ('title_generated', models.BooleanField(default=False, help_text='Indica se o título para esta vaga já foi gerado.')),
                ('work_schedule', models.CharField(blank=True, help_text='Horário e frequência de trabalho para a vaga.', max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Idade mínima recomendada para a vaga.', null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Solteiro(a)'), ('M', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], help_text='Estado civil do candidato desejado.', max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Gênero do candidato desejado.', max_length=1, null=True)),
                ('education_level', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ET', 'Ensino Médio Técnico'), ('TE', 'Tecnólogo'), ('GR', 'Graduação'), ('PG', 'Pós-graduação'), ('ME', 'Mestrado'), ('DR', 'Doutorado')], help_text='Nível de escolaridade exigido para a vaga.', max_length=2)),
                ('computer_skills', models.TextField(blank=True, help_text='Habilidades em informática necessárias para a vaga.')),
                ('languages', models.CharField(blank=True, help_text='Idiomas exigidos ou desejáveis para a vaga.', max_length=45, null=True)),
                ('job_responsibilities', models.TextField(blank=True, help_text='Principais atividades e responsabilidades da posição.')),
                ('professional_experience', models.TextField(blank=True, help_text='Experiência profissional exigida para a posição.')),
                ('behavioral_profile', models.TextField(blank=True, help_text='Perfil comportamental desejado para o candidato.')),
                ('work_environment', models.TextField(blank=True, help_text='Características do local de trabalho.')),
                ('additional_notes', models.TextField(blank=True, help_text='Observações gerais sobre a vaga.')),
                ('restrictions', models.TextField(blank=True, help_text='Restrições ou requisitos especiais para a posição.')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Motivo do cancelamento da vaga, se aplicável.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do perfil.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação no perfil.')),
                ('client', models.ForeignKey(default=1, help_text='Cliente associado a este perfil.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='clients.client')),
                ('client_contact', models.ForeignKey(default=1, help_text='Contato dentro da empresa cliente.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='clients.clientcontact')),
                ('fee', models.ForeignKey(default=1, help_text='Honorário associado ao serviço.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='clients.clientfee')),
                ('position', models.ForeignKey(default=1, help_text='Cargo associado ao perfil.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='hr.position')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
