# Generated by Django 5.1.4 on 2025-02-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_resume_education_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.TextField(blank=True)),
                ('personal_family_context', models.TextField(blank=True)),
                ('educational_background', models.TextField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('candidate_profile', models.TextField(blank=True)),
                ('career_objectives', models.TextField(blank=True)),
                ('final_considerations', models.TextField(blank=True)),
                ('agreed_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('candidate_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hr.profile')),
                ('resume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hr.resume')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
        ),
    ]
