# Generated by Django 5.1.4 on 2025-02-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='postal_code',
            new_name='cep',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='number',
        ),
    ]
