# Generated by Django 5.1.4 on 2025-02-24 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_resume_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together={('cpf', 'birth_date', 'user')},
        ),
    ]
