# Generated by Django 5.1.4 on 2025-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_resume_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
