# Generated by Django 5.1.4 on 2025-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_resume_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('M', 'Casado(a)'), ('D', 'Divorciado(a)'), ('W', 'Viúvo(a)')], help_text='Estado civil do candidato desejado.', max_length=1),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('M', 'Casado(a)'), ('D', 'Divorciado(a)'), ('W', 'Viúvo(a)')], help_text='Estado civil', max_length=1),
        ),
    ]
