# Generated by Django 5.1.4 on 2025-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cnh',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True),
        ),
    ]
