# Generated by Django 5.1.4 on 2025-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_resume_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ET', 'Ensino Médio Técnico'), ('GR', 'Graduação'), ('PG', 'Pós-graduação'), ('ME', 'Mestrado'), ('DR', 'Doutorado')], help_text='Nível de escolaridade exigido para a vaga.', max_length=2),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_level',
            field=models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ET', 'Ensino Médio Técnico'), ('GR', 'Graduação'), ('PG', 'Pós-graduação'), ('ME', 'Mestrado'), ('DR', 'Doutorado')], help_text='Nível de escolaridade', max_length=2),
        ),
    ]
