# Generated by Django 5.1.4 on 2025-03-26 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_client_trade_name_alter_clientcontact_name'),
        ('hr', '0019_alter_profile_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(default=1, help_text='Cliente associado a este perfil.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='clients.client', verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(default=1, help_text='Cargo associado ao perfil.', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='hr.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=45, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='neighborhood',
            field=models.CharField(max_length=45, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
