# Generated by Django 5.1.4 on 2025-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_alter_position_title_alter_profile_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado'), ('S', 'Seleção')], default='A', help_text='Status do perfil: Ativo (A), Inativo (I), Cancelado (C) ou Suspenso (S).', max_length=1),
        ),
    ]
