# Generated by Django 5.1.4 on 2025-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_report_options_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado'), ('S', 'Seleção')], default='A', help_text='Status do perfil: Aberto, Fechado, Cancelado, Seleção.', max_length=1),
        ),
    ]
