# Generated by Django 5.1.4 on 2025-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('EST', 'Estágio')], default='CLT', help_text='Tipo do contrato: CLT, PJ, Estágio.', max_length=3),
        ),
    ]
