# Generated by Django 5.1.4 on 2025-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_profile_contract_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='english_level',
            field=models.CharField(choices=[('N', 'Nenhum conhecimento'), ('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado'), ('F', 'Fluente')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='resume',
            name='spanish_level',
            field=models.CharField(choices=[('N', 'Nenhum conhecimento'), ('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado'), ('F', 'Fluente')], default='N', max_length=1),
        ),
    ]
