# Generated by Django 5.1.4 on 2025-04-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Currículo', 'verbose_name_plural': 'Currículos'},
        ),
    ]
