# Generated by Django 5.1.4 on 2025-04-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_alter_resume_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
    ]
