# Generated by Django 5.1.4 on 2025-04-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_remove_resume_cpf_remove_resume_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='professional_summary',
        ),
    ]
