# Generated by Django 5.1.4 on 2025-04-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_remove_report_professional_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
