# Generated by Django 5.1.4 on 2025-05-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_alter_resume_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.resume'),
        ),
    ]
