# Generated by Django 5.1.4 on 2025-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corporate_name', models.CharField(max_length=144)),
                ('trade_name', models.CharField(max_length=144)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=45)),
                ('neighborhood', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('state_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
    ]
