# Generated by Django 5.1.4 on 2025-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_created_alter_client_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='zip_code',
            new_name='cep',
        ),
        migrations.AlterField(
            model_name='client',
            name='corporate_name',
            field=models.CharField(help_text='Razão Social', max_length=144),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_of_employees',
            field=models.IntegerField(blank=True, help_text='Número de empregados', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state_registration',
            field=models.CharField(blank=True, help_text='Inscrição estadual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='trade_name',
            field=models.CharField(help_text='Nome fantasia', max_length=144),
        ),
    ]
