# Generated by Django 5.1.4 on 2025-01-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Ativo'), (False, 'Inativo')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'db_table': 'client_contact',
                'ordering': ['name'],
            },
        ),
    ]
