# Generated by Django 5.1.4 on 2025-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_rename_created_client_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=50)),
            ],
        ),
    ]
