# Generated by Django 5.1.4 on 2025-01-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientbenefit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientBenefit',
            new_name='Benefit',
        ),
    ]
