# Generated by Django 5.1.4 on 2025-02-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_economicactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='economic_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clients.economicactivity'),
        ),
    ]
