# Generated by Django 5.1.4 on 2025-02-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_economic_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economicactivity',
            options={'verbose_name': 'Atividade Econômica', 'verbose_name_plural': 'Atividades Econômicas'},
        ),
    ]
