# Generated by Django 5.1.4 on 2025-02-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_economicactivity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=60)),
                ('type_of_charge', models.IntegerField(blank=True, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'ordering': ['name'], 'verbose_name': 'Contato Cliente', 'verbose_name_plural': 'Contatos Clientes'},
        ),
    ]
