# Generated by Django 5.1.4 on 2025-02-07 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_service_alter_clientcontact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefício', 'verbose_name_plural': 'Benefícios'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.CreateModel(
            name='ClientFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clients.client')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clients.service')),
            ],
            options={
                'verbose_name': 'Honorário',
                'verbose_name_plural': 'Honorários',
            },
        ),
    ]
