# Generated by Django 5.1.4 on 2025-02-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_benefits_alter_benefit_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='economic_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.economicactivity'),
        ),
    ]
