# Generated by Django 5.1.4 on 2025-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_client_economic_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='benefits',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='clients.benefit'),
        ),
    ]
