# Generated by Django 5.1.4 on 2025-02-21 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_client_number_of_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfee',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clients.service'),
        ),
    ]
