# Generated by Django 5.1.4 on 2025-02-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_clientfee_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfee',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='clients.service'),
        ),
        migrations.AlterUniqueTogether(
            name='clientfee',
            unique_together={('client', 'service')},
        ),
    ]
