# Generated by Django 5.1.4 on 2025-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='trade_name',
            field=models.CharField(help_text='Nome fantasia', max_length=144, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
