# Generated by Django 5.1.4 on 2025-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_alter_client_trade_name_alter_clientcontact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição', max_length=144, null=True, verbose_name='Descrição'),
        ),
    ]
